### ISSUE TITLE
If you are using phone just use Share. From any repository to your repository

### ISSUE THREAD

**Issue by Harunadangabas** [calistus-igwilo/nitda-blockchain-scholarship#188]
If you are using phone just use Share. From any repository to your repository 

_Originally posted by @Salmabuba in https://github.com/calistus-igwilo/nitda-blockchain-scholarship/pull/146#issuecomment-1362628290_

**Comment by BossVNN** [comment]
on 5thwork.com, create an account with your email.  Simple!
