### ISSUE TITLE
reduction of scores

### ISSUE THREAD

**Issue by esybest** [calistus-igwilo/nitda-blockchain-scholarship#210]
I noticed a reduction of my course after I had struggled and got 56% last night, just to wake up this morning to see that my score has been reduced likewise other people in my telegram group.

PLEASE WHATEVER BE THE ERROR SHOULD BE FIXED.

**Comment by esybest** [comment]
TREAT AS URGENT, AM NOT READY TO REDO THIS STUFF.

**Comment by Dabai02** [comment]
Also me i score 92% but 88%

**Comment by Salmabuba** [comment]
Me too

**Comment by Salmabuba** [comment]
I can't access my account

**Comment by Musakl** [comment]
If anyone notice that there is reduction in his/her score, the best thing
to do is to go back and crosscheck his/her assessment to see whether it is
intact or not

**Comment by esybest** [comment]
How can I have access to my certificate please

**Comment by Salmabuba** [comment]
Buzzmint
