### ISSUE TITLE
Whitepaper PDF file won't open

### ISSUE THREAD

**Issue by Mckay0883** [calistus-igwilo/nitda-blockchain-scholarship#51]
Hi Sir,

The PDF file shared for reading doesn't open after downloading. Please can you help look into it.

Regards
Busayo

**Comment by heldworld** [comment]
hi. the documents open without any challenge, ensure to follow the attached image guide to download and then proceed to open with adobe pdf reader and microsoft word as the case may be.
![save files](https://user-images.githubusercontent.com/38360972/206908758-30711097-b066-4138-ae79-b690255c249d.jpg)

**Comment by Mckay0883** [comment]
Thank you, figured it out with your reply

**Comment by Abbannusee** [comment]
Very nice
